// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sphere/binding/binding.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package binding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BindingLocation specifies where an HTTP request parameter or body component
// is bound to a Protobuf message field. Used by protoc-gen-sphere-binding and
// protoc-gen-sphere code generators to produce Go struct tags and binder calls.
//
// Preconditions: Used during Protobuf schema definition. QUERY, URI, and HEADER
// locations are valid only on scalar types (numeric, string, bool) and well-known scalar types.
// Concurrency: Enum values are immutable and safe for concurrent use.
// Lifecycle: Handled statically at code generation time; descriptors are registered at init().
// Error semantics: Invalid locations for complex types are rejected at code-generation time.
// Side-effects: Pure schema metadata; no runtime background tasks or context mutation.
type BindingLocation int32

const (
	// BINDING_LOCATION_UNSPECIFIED is the default zero value; indicates no explicit
	// binding location is specified. Falls back to message default_location if set.
	BindingLocation_BINDING_LOCATION_UNSPECIFIED BindingLocation = 0
	// BINDING_LOCATION_QUERY binds the field to HTTP URL query parameters (e.g. `?name=val`).
	// Generates `query:"<name>"` struct tag. Supported only on scalar and well-known scalar types.
	BindingLocation_BINDING_LOCATION_QUERY BindingLocation = 1
	// BINDING_LOCATION_URI binds the field to URL path/route parameters (e.g. `/users/:id`).
	// Generates `uri:"<name>"` struct tag. Supported only on scalar and well-known scalar types.
	BindingLocation_BINDING_LOCATION_URI BindingLocation = 2
	// BINDING_LOCATION_JSON binds the field to the HTTP request JSON body.
	// Preserves standard `json:"<name>"` tag.
	BindingLocation_BINDING_LOCATION_JSON BindingLocation = 3
	// BINDING_LOCATION_FORM binds the field to HTTP form or multipart/form-data body parameters.
	// Generates `form:"<name>"` struct tag.
	BindingLocation_BINDING_LOCATION_FORM BindingLocation = 4
	// BINDING_LOCATION_HEADER binds the field to HTTP request headers.
	// Generates `header:"<name>"` struct tag. Supported only on scalar and well-known scalar types.
	BindingLocation_BINDING_LOCATION_HEADER BindingLocation = 5
)

// Enum value maps for BindingLocation.
var (
	BindingLocation_name = map[int32]string{
		0: "BINDING_LOCATION_UNSPECIFIED",
		1: "BINDING_LOCATION_QUERY",
		2: "BINDING_LOCATION_URI",
		3: "BINDING_LOCATION_JSON",
		4: "BINDING_LOCATION_FORM",
		5: "BINDING_LOCATION_HEADER",
	}
	BindingLocation_value = map[string]int32{
		"BINDING_LOCATION_UNSPECIFIED": 0,
		"BINDING_LOCATION_QUERY":       1,
		"BINDING_LOCATION_URI":         2,
		"BINDING_LOCATION_JSON":        3,
		"BINDING_LOCATION_FORM":        4,
		"BINDING_LOCATION_HEADER":      5,
	}
)

func (x BindingLocation) Enum() *BindingLocation {
	p := new(BindingLocation)
	*p = x
	return p
}

func (x BindingLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_sphere_binding_binding_proto_enumTypes[0].Descriptor()
}

func (BindingLocation) Type() protoreflect.EnumType {
	return &file_sphere_binding_binding_proto_enumTypes[0]
}

func (x BindingLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingLocation.Descriptor instead.
func (BindingLocation) EnumDescriptor() ([]byte, []int) {
	return file_sphere_binding_binding_proto_rawDescGZIP(), []int{0}
}

var file_sphere_binding_binding_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*BindingLocation)(nil),
		Field:         136655300,
		Name:          "sphere.binding.default_location",
		Tag:           "varint,136655300,opt,name=default_location,enum=sphere.binding.BindingLocation",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         136655301,
		Name:          "sphere.binding.default_auto_tags",
		Tag:           "bytes,136655301,rep,name=default_auto_tags",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*BindingLocation)(nil),
		Field:         136655310,
		Name:          "sphere.binding.default_oneof_location",
		Tag:           "varint,136655310,opt,name=default_oneof_location,enum=sphere.binding.BindingLocation",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         136655311,
		Name:          "sphere.binding.default_oneof_auto_tags",
		Tag:           "bytes,136655311,rep,name=default_oneof_auto_tags",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*BindingLocation)(nil),
		Field:         136655320,
		Name:          "sphere.binding.location",
		Tag:           "varint,136655320,opt,name=location,enum=sphere.binding.BindingLocation",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         136655321,
		Name:          "sphere.binding.tags",
		Tag:           "bytes,136655321,rep,name=tags",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         136655322,
		Name:          "sphere.binding.auto_tags",
		Tag:           "bytes,136655322,rep,name=auto_tags",
		Filename:      "sphere/binding/binding.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// default_location defines the default BindingLocation for all fields in this message
	// that do not specify their own field-level location option.
	// Preconditions: Must be a valid BindingLocation enum value.
	// Concurrency: Extension descriptors are immutable after registration in init().
	//
	// optional sphere.binding.BindingLocation default_location = 136655300;
	E_DefaultLocation = &file_sphere_binding_binding_proto_extTypes[0]
	// default_auto_tags specifies tag keys (e.g. "form", "json") that should be automatically
	// generated with the field's proto name for all fields in this message.
	// Preconditions: Tag keys must be non-empty and must not contain spaces or quotes.
	// Concurrency: Slices returned by GetExtension are direct references; callers must not mutate concurrently.
	//
	// repeated string default_auto_tags = 136655301;
	E_DefaultAutoTags = &file_sphere_binding_binding_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// default_oneof_location defines the default BindingLocation for all fields within this oneof group.
	// Preconditions: Must be a valid BindingLocation enum value.
	// Concurrency: Extension descriptors are immutable after registration in init().
	//
	// optional sphere.binding.BindingLocation default_oneof_location = 136655310;
	E_DefaultOneofLocation = &file_sphere_binding_binding_proto_extTypes[2]
	// default_oneof_auto_tags specifies tag keys automatically generated for fields within this oneof group.
	// Preconditions: Tag keys must be non-empty and must not contain spaces or quotes.
	// Concurrency: Slices returned by GetExtension are direct references; callers must not mutate concurrently.
	//
	// repeated string default_oneof_auto_tags = 136655311;
	E_DefaultOneofAutoTags = &file_sphere_binding_binding_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// location overrides default_location for this specific field.
	// Preconditions: Must be a valid BindingLocation. QUERY/URI/HEADER restricted to scalar types.
	// Concurrency: Extension descriptors are immutable after registration in init().
	//
	// optional sphere.binding.BindingLocation location = 136655320;
	E_Location = &file_sphere_binding_binding_proto_extTypes[4]
	// tags specifies explicit Go struct tag strings to apply to the generated field
	// (e.g. 'validate:"required,min=1"'). Each string must be valid Go struct tag syntax.
	// Preconditions: Must conform to standard Go struct tag key:"value" syntax.
	// Concurrency: Slices returned by GetExtension are direct references; callers must not mutate concurrently.
	//
	// repeated string tags = 136655321;
	E_Tags = &file_sphere_binding_binding_proto_extTypes[5]
	// auto_tags specifies tag keys (e.g. "param", "schema") to generate for this field using the field's name.
	// Preconditions: Tag keys must be non-empty and must not contain spaces or quotes.
	// Concurrency: Slices returned by GetExtension are direct references; callers must not mutate concurrently.
	//
	// repeated string auto_tags = 136655322;
	E_AutoTags = &file_sphere_binding_binding_proto_extTypes[6]
)

var File_sphere_binding_binding_proto protoreflect.FileDescriptor

const file_sphere_binding_binding_proto_rawDesc = "" +
	"\n" +
	"\x1csphere/binding/binding.proto\x12\x0esphere.binding\x1a google/protobuf/descriptor.proto*\xbc\x01\n" +
	"\x0fBindingLocation\x12 \n" +
	"\x1cBINDING_LOCATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BINDING_LOCATION_QUERY\x10\x01\x12\x18\n" +
	"\x14BINDING_LOCATION_URI\x10\x02\x12\x19\n" +
	"\x15BINDING_LOCATION_JSON\x10\x03\x12\x19\n" +
	"\x15BINDING_LOCATION_FORM\x10\x04\x12\x1b\n" +
	"\x17BINDING_LOCATION_HEADER\x10\x05:q\n" +
	"\x10default_location\x12\x1f.google.protobuf.MessageOptions\x18\xc4\xe3\x94A \x01(\x0e2\x1f.sphere.binding.BindingLocationR\x0fdefaultLocation\x88\x01\x01:N\n" +
	"\x11default_auto_tags\x12\x1f.google.protobuf.MessageOptions\x18\xc5\xe3\x94A \x03(\tR\x0fdefaultAutoTags:z\n" +
	"\x16default_oneof_location\x12\x1d.google.protobuf.OneofOptions\x18\xce\xe3\x94A \x01(\x0e2\x1f.sphere.binding.BindingLocationR\x14defaultOneofLocation\x88\x01\x01:W\n" +
	"\x17default_oneof_auto_tags\x12\x1d.google.protobuf.OneofOptions\x18\xcf\xe3\x94A \x03(\tR\x14defaultOneofAutoTags:`\n" +
	"\blocation\x12\x1d.google.protobuf.FieldOptions\x18\xd8\xe3\x94A \x01(\x0e2\x1f.sphere.binding.BindingLocationR\blocation\x88\x01\x01:4\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\xd9\xe3\x94A \x03(\tR\x04tags:=\n" +
	"\tauto_tags\x12\x1d.google.protobuf.FieldOptions\x18\xda\xe3\x94A \x03(\tR\bautoTagsB\xa8\x01\n" +
	"\x12com.sphere.bindingB\fBindingProtoP\x01Z+github.com/go-sphere/binding/sphere/binding\xa2\x02\x03SBX\xaa\x02\x0eSphere.Binding\xca\x02\x0eSphere\\Binding\xe2\x02\x1aSphere\\Binding\\GPBMetadata\xea\x02\x0fSphere::Bindingb\x06proto3"

var (
	file_sphere_binding_binding_proto_rawDescOnce sync.Once
	file_sphere_binding_binding_proto_rawDescData []byte
)

func file_sphere_binding_binding_proto_rawDescGZIP() []byte {
	file_sphere_binding_binding_proto_rawDescOnce.Do(func() {
		file_sphere_binding_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sphere_binding_binding_proto_rawDesc), len(file_sphere_binding_binding_proto_rawDesc)))
	})
	return file_sphere_binding_binding_proto_rawDescData
}

var file_sphere_binding_binding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sphere_binding_binding_proto_goTypes = []any{
	(BindingLocation)(0),                // 0: sphere.binding.BindingLocation
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.OneofOptions)(nil),   // 2: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_sphere_binding_binding_proto_depIdxs = []int32{
	1,  // 0: sphere.binding.default_location:extendee -> google.protobuf.MessageOptions
	1,  // 1: sphere.binding.default_auto_tags:extendee -> google.protobuf.MessageOptions
	2,  // 2: sphere.binding.default_oneof_location:extendee -> google.protobuf.OneofOptions
	2,  // 3: sphere.binding.default_oneof_auto_tags:extendee -> google.protobuf.OneofOptions
	3,  // 4: sphere.binding.location:extendee -> google.protobuf.FieldOptions
	3,  // 5: sphere.binding.tags:extendee -> google.protobuf.FieldOptions
	3,  // 6: sphere.binding.auto_tags:extendee -> google.protobuf.FieldOptions
	0,  // 7: sphere.binding.default_location:type_name -> sphere.binding.BindingLocation
	0,  // 8: sphere.binding.default_oneof_location:type_name -> sphere.binding.BindingLocation
	0,  // 9: sphere.binding.location:type_name -> sphere.binding.BindingLocation
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	7,  // [7:10] is the sub-list for extension type_name
	0,  // [0:7] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sphere_binding_binding_proto_init() }
func file_sphere_binding_binding_proto_init() {
	if File_sphere_binding_binding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sphere_binding_binding_proto_rawDesc), len(file_sphere_binding_binding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_sphere_binding_binding_proto_goTypes,
		DependencyIndexes: file_sphere_binding_binding_proto_depIdxs,
		EnumInfos:         file_sphere_binding_binding_proto_enumTypes,
		ExtensionInfos:    file_sphere_binding_binding_proto_extTypes,
	}.Build()
	File_sphere_binding_binding_proto = out.File
	file_sphere_binding_binding_proto_goTypes = nil
	file_sphere_binding_binding_proto_depIdxs = nil
}
